apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inventree.fullname" . }}
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "inventree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "inventree.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '-c']
          args:
            - >
              invoke migrate &&
              invoke static
          volumeMounts:
            - name: inventree-data
              mountPath: /home/inventree/data
          env:
            - name: INVENTREE_SITE_URL
              value: {{ .Values.global.siteUrl }}
          {{- (include "inventree.renderSecrets" (dict "data" .Values.global.dbSecrets)) | nindent 10 -}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inventree.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: INVENTREE_SITE_URL
              value: {{ .Values.global.siteUrl }}
            {{- if not (empty .Values.global.cacheSecrets) }}
            - name: INVENTREE_CACHE_ENABLED
              value: "True"
            {{- end -}}
            {{- if .Values.plugins.enabled }}
            - name: INVENTREE_PLUGINS_ENABLED
              value: "True"
            {{- end }}
          {{- (include "inventree.renderSecrets" (dict "data" .Values.global.cacheSecrets)) | nindent 10 -}}
          {{- (include "inventree.renderSecrets" (dict "data" .Values.global.dbSecrets)) | nindent 10 -}}
          {{- if .Values.global.adminSecret }}
          envFrom:
            - secretRef:
                name: "{{ .Values.global.adminSecret }}"
          {{- end }}
          {{/*
          # Disabled temporary, due to `... does not match the SITE_URL errors`
          # https://github.com/inventree/InvenTree/issues/10331
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          */}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: inventree-data
              mountPath: /home/inventree/data
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: inventree-proxy
          image: {{ .Values.serviceProxy.image }}:{{ .Values.serviceProxy.tag}}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxy-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
            - name: inventree-data
              mountPath: /var/www
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: proxy-conf
          configMap:
            name: nginx-proxy-config
        - name: inventree-data
          persistentVolumeClaim:
            claimName: inventree-data
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
